plugins {
  ${if Java}
  id 'java'
  ${end}
  ${if Application}
  id 'application'
  ${end}
}
${if Java}
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(${JvmVersion})
  }
}
${end}
group = '${Org}'
version = '${Version}'
description = '${Description}'
${if Java}
repositories {
  mavenCentral()
}
dependencies {
}
${end}
